### PR TITLE
data organization

### PR DESCRIPTION
**Pull request by zzbalews**
I changed the data hashes check to look for files based on our new organization (see README.md and  #27 ). The project-red/data/hashes is my list of files we're all going to use. Is anything missing?

### CODE REVIEW

**Comment by zzbalews** [comment]
I'm not sure how to deal with the missing coverage here because testing those sections of code would intentionally trigger errors. Is there a way to write tests that expect raised errors so the tests don't fail for the wrong reason?

One section is the main() function for the file we'll use to check that all of the necessary files exist in the data folder. Since we're not putting those files on github, executing the function would raise an error.

The other is a case in which a file by the correct name exists but its hash doesn't match what is expected.

**Comment by jcbmiller94** [comment]
Hey, just saw all this. Yeah, I agree the lack of coverage seems to be very limited to the main() function or the areas where an assertion error is raised. Perhaps this function may help? It seems to take some sort of exception https://docs.scipy.org/doc/numpy/reference/generated/numpy.testing.assert_raises.html#numpy.testing.assert_raises

Or some function that conducts a test that fails if it doesn't receive an error, as you said.

**Comment by jcbmiller94** [comment]
I think that writing the function to check all of the data when downloaded correctly, even if it fails on Github, is the way to go. This way someone getting the USB with the .nii files on them could still validate their correctness, we could just add it to the README file here that the test will only pass for the checked data when it's set up in the correct way, as specified. 

Or, is there some way we could put placeholder files with the same name up? Although I guess the hashes would be different...

**Comment by jcbmiller94** [comment]
Also, maybe this is on topic with this pull request but it'd be great to organize a common output of plots as well as results, perhaps? And place the images into a common folder along with the results?

**Comment by ctseng12** [comment]
Re unexpected hash: I haven't used assert_raises before but it looks like it could work; a try/except block to catch the ValueError might also work?

**Comment by zzbalews** [comment]
@jcbmiller94 I was thinking that we could save the outputs of each section in the data/ds000030/sub-#####/*_results directories. But do you want to have a different location for plots?

@ctseng12 @jcbmiller94 thanks for the suggestions. I'll try a few things and let you know what works!

**Comment by zzbalews** [comment]
Success! Not sure if this is the best way, but it works :)

For a function that raises an error (like the hash doesn't match):
`try:`
`	some_function()`
`except ValueError:`
`	print('expected to fail')`

For testing the main():
`try:`
`	os.system('python3 script.py')`
`except FileNotFoundError:`
`	print('testing main(); expected to fail')`

Ready to merge if everyone approves

**Comment by jcbmiller94** [comment]
Nice work!! That `except` tick is pretty nifty! 

And yeah - keeping the plots along with the results makes sense. Just thinking of a way we could tie all the code output/results together into a 'report' of sorts

**Comment by ctseng12** [comment]
whoo nice, I'll merge 

Putting each plot in the relevant results folder makes more sense to me but the other way works too

**Pull request merged**
